name: 'Update Changelog'

on:
  release:
    types: [released]

jobs:
  call-workflow-update-changelog:
    uses: figuren-theater/.github/.github/workflows/update-changelog.yml@main
    secrets: inherit

